In [ ]:
import numpy as np


arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [ ]:
arr = np.full((3,4),3)
print(arr)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
square_arr = np.arange(0, 10, 2)
print(square_arr)

[0 2 4 6 8]


In [ ]:
square_arr = np.arange(2, 10, 2)
print(square_arr)

[2 4 6 8]


In [ ]:
square_arr = np.arange(0, 10, 3)
print(square_arr)

[0 3 6 9]


In [ ]:
square_arr = np.arange(10, 21, 2)
print(square_arr)

[10 12 14 16 18 20]


In [ ]:
square_arr = np.arange(10, 51, 4)
print(square_arr)

[10 14 18 22 26 30 34 38 42 46 50]


In [ ]:
lin_space = np.linspace(1, 5, 10)
print(lin_space)
# ( destination - source ) / total number of digit - 1

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [9]:
# Array Properties

arr = np.array([[1, 2, 3,8], [4, 5, 6,9]])
print(arr.shape)  # (rows, columns)
print(arr.size)   # Total elements
print(arr.ndim)   # Number of dimensions
print(arr.dtype)  # Data type of elements

(2, 4)
8
2
int64


In [10]:
# Reshape and Flatten

# Reshape (2x3 to 3x2)
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)
# Flatten (convert multi-dimensional array to 1D)
flattened_arr = arr.flatten()
print(flattened_arr)

ValueError: cannot reshape array of size 8 into shape (3,2)

In [14]:
# Mathematical Operations

a = np.array([1, 2, 3, 8])
b = np.array([4, 5, 6, 89])
print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division
print(a ** 2)  # Element-wise power
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]]) # 1  2     5  6
mat2 = np.array([[5, 6], [7, 8]]) # 3  4     7  8
dot_product = np.dot(mat1, mat2)
print(dot_product)

[ 5  7  9 97]
[ -3  -3  -3 -81]
[  4  10  18 712]
[0.25       0.4        0.5        0.08988764]
[ 1  4  9 64]
[[19 22]
 [43 50]]


In [6]:
# 9 aggregate Function
import numpy as np

arr = np.array([1, 2, 43, 4, 5])

print(np.sum(arr))     # Sum of elements
print(np.mean(arr))    # Mean
print(np.median(arr))  # Median
print(np.std(arr))     # Standard deviation
print(np.var(arr))     # Variance
print(np.min(arr))     # Minimum value
print(np.max(arr)) #maximum

55
11.0
4.0
16.06237840420901
258.0
1
43


In [19]:
#  Indexing & Slicing

arr = np.array([10, 20, 30, 40, 50])
print(arr[1])        # Access single element (index 1)
print(arr[1:4])      # Slice elements from index 1 to 3
print(arr[:3])       # First 3 elements
print(arr[-2:])      # Last 2 elements
# 2D array indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[0, 1])    # Row 0, Column 1
print(arr2d[:, 1])    # All rows, Column 1
print(arr2d[1, :])    # Row 1, All columns

20
[20 30 40]
[10 20 30]
[40 50]
2
[2 5]
[4 5 6]


In [20]:
#Filtering Data
arr = np.array([10, 20, 30, 40, 50])
# Condition-based filtering
filtered_arr = arr[arr > 20]
print(filtered_arr)

[30 40 50]


In [21]:
# Stacking Arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# Vertical stack
v_stack = np.vstack((a, b))
print(v_stack)
# Horizontal stack
h_stack = np.hstack((a, b))
print(h_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [25]:
# Splitting Arrays

arr = np.array([1, 2, 3, 4, 5, 6, 5, 9, 5, 8])
# Split into 3 parts
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([1, 2, 3, 4]), array([5, 6, 5]), array([9, 5, 8])]


In [38]:
 #Copy vs View


arr = np.array([1, 2, 3])
# View (changes in view affect the original)
view_arr = arr.view()
view_arr[0] = 87
print(arr)
# Copy (changes in copy do not affect the original)
copy_arr = arr.copy()
copy_arr[0] = 50
print(arr)


arrr = np.array([30,80])
newArr = arrr.copy()
newArr[0] = 20
print(arrr)

[87  2  3]
[87  2  3]
[30 80]


In [47]:
# python np sort arr
arr = np.array([3, 1, 4, 1, 5, 9, 8, 90, 60, 3, 6, 4, 76])
sorted_arr = np.sort(arr)
newArr = sorted_arr[sorted_arr <= 10] #filter
print(sorted_arr)
print(newArr)

[ 1  1  3  3  4  4  5  6  8  9 60 76 90]
[1 1 3 3 4 4 5 6 8 9]


In [50]:
#Install Pandas

import pandas as pd

data = { # this is an dictionary
'Name': ['Alice', 'Bob', 'Charlie', 'Rabi'],
'Age': [25, 30, 35, '40'],
'City': ['New York', 'London', 'Paris', 'Rabi']
}
df = pd.DataFrame(data) # dictionary converted to datafream
print(df)

      Name Age      City
0    Alice  25  New York
1      Bob  30    London
2  Charlie  35     Paris
3     Rabi  40      Rabi
